# Generated by Django 3.2.12 on 2023-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('vend_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('u_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('lisence_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vender',
                'managed': False,
            },
        ),
    ]
