# Generated by Django 3.2.12 on 2023-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000)),
                ('finction_id', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('event_team_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'decoration',
                'managed': False,
            },
        ),
    ]
