# Generated by Django 3.2.12 on 2022-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=50)),
                ('d_address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dealer',
                'managed': False,
            },
        ),
    ]
