# Generated by Django 3.2.12 on 2022-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
