# Generated by Django 3.2.12 on 2023-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriumFeedback',
            fields=[
                ('af_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('u_id', models.IntegerField()),
                ('aud_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auditorium_feedback',
                'managed': False,
            },
        ),
    ]
