# Generated by Django 3.2.12 on 2023-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('ph_id', models.AutoField(primary_key=True, serialize=False)),
                ('studio_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('rate_photo', models.IntegerField()),
                ('rate_video', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'photography',
                'managed': False,
            },
        ),
    ]
