# Generated by Django 3.2.19 on 2024-01-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFeedback',
            fields=[
                ('pf_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('ph_id', models.IntegerField()),
            ],
            options={
                'db_table': 'photo_feedback',
                'managed': False,
            },
        ),
    ]
