# Generated by Django 3.2.12 on 2022-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('aud_id', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('upi_id', models.IntegerField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
