# Generated by Django 3.2.12 on 2022-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ab_id', models.AutoField(primary_key=True, serialize=False)),
                ('aud_id', models.IntegerField()),
                ('u_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_of_days', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('booking_time', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
    ]
