# Generated by Django 3.2.12 on 2023-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodbook',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'foodbook',
                'managed': False,
            },
        ),
    ]
