# Generated by Django 3.2.12 on 2023-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photobook',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'photobook',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Foodbook',
        ),
    ]
